version: '3.8'
services:

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: MyPowerFullRootPasswordWith2@@And4$$$$  
      MYSQL_DATABASE: Locations_DataBase       
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  python-app:
    build:
      context: ./pythonScripts
      dockerfile: Dockerfile
    container_name: python-app
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: MyPowerFullRootPasswordWith2@@And4$$$$
      MYSQL_DATABASE: Locations_DataBase   
    depends_on:
      - mysql-db
    networks:
      - app-network

  dotnet-api:
    build:
      context: ./ApplicationWebApi
      dockerfile: Dockerfile
    container_name: dotnet-api
    environment:
      - TravelConnectionString=Server=mysql-db;Database=Locations_DataBase;User=root;Password=MyPowerFullRootPasswordWith2@@And4$$$$;
    ports:
      - "5000:80"
    depends_on:
      - mysql-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
